Develop
Chegulov/java-filmorate pull request #22
Opened 2024-01-06 22:13 UTC by Chegulov

2024-01-08 06:37 UTC, avlin87 requested changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде.
Молодцы, что сделали все задания.
Вы хорошо разобрались во взаимодействие между слоями сервис контроллер репозиторий. У вас получились хорошие запросы к таблицам.

В описании пул-реквеста или в файле readme добавьте, пожалуйста, описание того, какие задачи выполнила группа.

2024-01-08 06:37 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
`Можно лучше`
Можно убрать конструктор заменив его аннотацией @RequiredArgsConstructor.

2024-01-08 06:37 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          filmService.getFilmStorage().create(film);
В этом классе контроллере зачем-то из сервиса `filmService`, как из класса модели, получаем объект класса `FilmStorage` и работаем напрямую с ним.

Контроллер должен работать с методами сервиса. А уже сервис сам должен обращаться к FilmStorage.
Исправь, пожалуйста.

2024-01-08 06:37 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Request received: GET /films/search");
`Можно лучше`
Уровень логирования лучше изменить с info на debug.
Логирование снижает производительность приложения. Поэтому лучше не заполнять логи лишней информацией без необходимости.

2024-01-08 06:37 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        int userId = reviewService.getReviewStorage().getReviewById(id).getUserId();
Контроллер должен обращаться к методам сервиса, а уже сервис должен обращаться к объекту storage.
Поправь, пожалуйста, во всем классе.

2024-01-08 06:37 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          return userService.getUserStorage().getUsers();
Контроллер должен обращаться к методам сервиса, а уже сервис должен обращаться к объекту storage.
Поправь, пожалуйста, во всем классе.

2024-01-08 14:13 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
заменил

2024-01-08 14:13 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          filmService.getFilmStorage().create(film);
сделаны вызовы методов сервиса

2024-01-08 14:16 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Request received: GET /films/search");
заменено

2024-01-08 14:26 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        int userId = reviewService.getReviewStorage().getReviewById(id).getUserId();
исправлено

2024-01-08 14:26 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          return userService.getUserStorage().getUsers();
исправлено

2024-01-09 16:24 UTC, avlin87 approved these changes
Спасибо за исправления, работу принимаю.

2024-01-09 19:13 UTC, merged