Controllers films users
Chegulov/java-filmorate pull request #4
Opened 2023-10-31 22:20 UTC by Chegulov

2023-11-01 19:46 UTC, avlin87 requested changes
Привет, Алексей,
Работа выглядит хорошо, смотри, пожалуйста, комментарии.

2023-11-01 19:46 UTC, avlin87 commented on pom.xml
> +
Отформатируй, пожалуйста, файл, чтобы структура была визуально очевидно.
Быстрые клавиши, как и в Java файлах:
На Windows в IntelliJ IDEA
Ctrl + Alt + L - форматирование кода

2023-11-01 19:46 UTC, avlin87 commented on pom.xml
> +            <version>1.18.20</version>
Версии зависимостей лучше вынести в проперти.
Быстрые клавиши Ctrl + Alt + V на значении.

Для остальных тоже, пожалуйста.

2023-11-01 19:46 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Logger log = LoggerFactory.getLogger(FilmController.class);
Эту строку можно удалить, и вместо неё добавить аннотацию ломбока @Slf4j на класс.
Переменная log будет ею инициализирована и так же останется в классе.

2023-11-01 19:46 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Logger log = LoggerFactory.getLogger(UserController.class);
Можно заменить на @Slf4j.

2023-11-01 21:13 UTC, avlin87 requested changes
Добавил два комментария.

2023-11-01 21:13 UTC, avlin87 commented on pom.xml
> +        </dependency>
Верни, пожалуйста, тэг version (без него может обойтись только зависимости от org.springframework.boot).
Без него не будет загружаться библиотека нужной версии.
<version>${lombok.version}</version>

Если бы воспользовался сочетанием клавишь Ctrl+Alt+V то эта операция должна была произойти автоматически.

2023-11-01 21:13 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Film> update(@RequestBody Film film) {
(можно оставить так же)
Я не понимаю зачем использовать ResponseEntity (Подскажи, пожалуйста, если я понял/не понял причину в рассуждениях ниже).
В остальных местах возвращаешь же сущность напрямую - тут можно было бы так же, Spring автоматически её преобразует. 
Или это, чтобы получить статус NotFound в ответе? Тогда можно было бы выбросить исключение throw new ResponseStatusException(HttpStatus.NOT_FOUND) тогда код был бы в одном стиле.

2023-11-01 21:16 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Film> update(@RequestBody Film film) {
спасибо, это именно для получения статуса 404

2023-11-03 00:57 UTC, avlin87 approved these changes
Работу принимаю.

2023-11-05 14:03 UTC, merged