Add database
Chegulov/java-filmorate pull request #6
Opened 2023-12-10 11:16 UTC by Chegulov

2023-12-11 07:19 UTC, avlin87 requested changes
Привет, Алексей,
Отличная работа, комментарии только "можно лучше".

2023-12-11 07:19 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public GenreController(GenreService genreService) {
`*Можно лучше*`
можно убрать конструктор, заменив его аннотацией `@RequiredArgsConstructor` - final поля будут ожидать инициализации в конструкторе.

2023-12-11 07:19 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    public MpaController(MpaService mpaService) {
`можно лучше`
так же как и в GenreController при желание можно избавиться от конструктора.

2023-12-11 07:19 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import java.util.*;
`*можно лучше*`
принято записывать каждый импорт отдельно, а не через `*`
в настройках идеии можно выставить чтобы она не пыталась объединить импорты при их оптимизации.

2023-12-11 15:33 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import java.util.*;
исправлено

2023-12-11 15:34 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    public MpaController(MpaService mpaService) {
заменил, спасибо

2023-12-11 15:34 UTC, Chegulov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public GenreController(GenreService genreService) {
заменил, спасибо

2023-12-12 06:45 UTC, avlin87 approved these changes
Работу принимаю.

2023-12-12 15:28 UTC, merged